spring:
  data:
    redis:
      host: redis
      port: 6379

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            enable: 'true'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.meta.ua
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: '465'

mail:
  template:
    path:
      user: templates/msg_for_user.html
      museum: templates/msg_for_museum.html
  museum:
    email: ${MAIL_USER}
    label: Museum.ua

logging:
  file:
    name: logfile.log
  pattern:
    file: "%replace(%msg){'\\u001B\\[[;\\d]*m', ''}%n"
  level:
    root: info
    web: info

resources:
  files:
    images:
      root: 'images'
      original: 'original'
      compressed: 'compressed'
      temporary: 'temp'

users:
  root:
    credentials:
      username: 'root'
      password: 'password'

images:
  desktop:
    width: 1280
    quality: 1
  preview:
    width: 768
    quality: 1
